### ISSUE TITLE
angsd-wrapper ngsF.sh error

### ISSUE THREAD

**Issue by ChaochihL** [mojaveazure/angsd-wrapper#1]
This is the error message when I ran the ngsF wrapper:

line 68: [[: ngsF.sh: syntax error: invalid arithmetic operator (error token is ".sh")

**Comment by mojaveazure** [comment]
I'm unable to reproduce the error. What does your configuration file look like?

**Comment by mojaveazure** [comment]
Make sure you're calling the wrappers correctly. So, for ngsF, use the following command:

``` shell
angsd-wrapper ngsF ~/path/to/config/ngsF_Config
```
