### ISSUE TITLE
Example data on figshare

### ISSUE THREAD

**Issue by arundurvasula** [mojaveazure/angsd-wrapper#10]
I uploaded the example data to figshare so we don't need to worry about iPlant issues: https://dx.doi.org/10.6084/m9.figshare.2063442

**Comment by mojaveazure** [comment]
Is there a way to download the dataset using Wget or Curl when hosted on figshare? I can't seem to find a direct download link.

**Comment by rossibarra** [comment]
THere's a download button, but not sure a wget link.

-Jeff

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by arundurvasula** [comment]
If you wget the red download link it should work:

`wget --no-check-certificate https://ndownloader.figshare.com/files/3667101`

On Thu, Jan 14, 2016 at 2:25 PM, Jeffrey Ross-Ibarra <
notifications@github.com> wrote:

> THere's a download button, but not sure a wget link.
> 
> -Jeff
> 
> ---
> 
> Jeffrey Ross-Ibarra
> 
> Dept. of Plant Sciences
> 262 Robbins Hall, Mail Stop 4
> University of California
> One Shields Ave
> Davis, CA 95616
> 
> Tel: 530-752-1152
> @jrossibarra
> www.rilab.org
> 
> On Thu, Jan 14, 2016 at 2:12 PM, Paul Hoffman notifications@github.com
> wrote:
> 
> > Is there a way to download the dataset using Wget or Curl when hosted on
> > figshare? I can't seem to find a direct download link.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/mojaveazure/angsd-wrapper/issues/10#issuecomment-171798312
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mojaveazure/angsd-wrapper/issues/10#issuecomment-171801408
> .

## 

Arun Durvasula
arun.durvasula@gmail.com

**Comment by mojaveazure** [comment]
Thanks Arun!
