### ISSUE TITLE
"N_CHROM" not used

### ISSUE THREAD

**Issue by lilei1** [mojaveazure/angsd-wrapper#14]
in this script "angsd-wrapper/Wrappers/Site_Frequency_Spectrum.sh", "N_CHROM" was clarified but not used. I am not sure if there is a parameter "N_CHROM" missed.

**Comment by arundurvasula** [comment]
I think `N_CHROM` is left over from the old version of ANGSD-wrapper ([1](https://github.com/arundurvasula/angsd-wrapper/blob/master/scripts/SFS.sh#L127)) (which used an older version of ANGSD) which required an `N_CHROM` argument for realSFS. It looks like the current version no longer requires it so we can safely remove it ([2](http://popgen.dk/angsd/index.php/RealSFS)). Thanks for pointing this out!
