### ISSUE TITLE
correct the path in the tutorial 

### ISSUE THREAD

**Issue by lilei1** [mojaveazure/angsd-wrapper#17]
The path" SAMPLE_INBREEDING=${HOME}/software/angsd-wrapper/iplant/Maize_Inbreeding.indF" in tutorial (https://github.com/mojaveazure/angsd-wrapper/wiki/Tutorial) should be "${HOME}/software/angsd-wrapper/Example_Data/Maize/Maize_Inbreeding.indF"

**Comment by mojaveazure** [comment]
FIxed
