### ISSUE TITLE
another error in the tutorial

### ISSUE THREAD

**Issue by lilei1** [mojaveazure/angsd-wrapper#18]
"REF_SEQ=${HOME}/software/angsd-wrapper/Example_Data/Sequences/Zea_mays.AGPv3.22.dna.chromosome.fa" should be "REF_SEQ=${HOME}/software/angsd-wrapper/Example_Data/Sequences/Zea_mays.AGPv3.30.dna_sm.chromosome.10.fa"

**Comment by mojaveazure** [comment]
It should be `REF_SEQ=${HOME}/software/angsd-wrapper/Example_Data/Sequences/Zea_mays.AGPv3.30.dna_sm.chromosome.10.fa`
