### ISSUE TITLE
Help.sh?

### ISSUE THREAD

**Issue by tvkent** [mojaveazure/angsd-wrapper#24]
I don't see any mention of this in the tutorial, but it looks useful.  Add a mention on the front page of the wiki?

**Comment by mojaveazure** [comment]
I started this, but there's quite a bit that I was going to do with it. Since it isn't done, I haven't made any mentions of it. I was planning on implementing it as a minor release bump later.

**Comment by tvkent** [comment]
Got it, sounds good.
