### ISSUE TITLE
setup fail

### ISSUE THREAD

**Issue by rossibarra** [mojaveazure/angsd-wrapper#27]
Just downloaded recent (commit eb3d0b95ce5e2f760b70d260cc0e771c40590ed4) AW and ran setup. I get:

gcc -c -Wall -O3  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=1 -I. knetfile.c -o knetfile.o
gcc -Wall -O3  -o bgzip bgzf.o bgzip.o knetfile.o -lz
g++ -O3 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE  -c parse_args.cpp
g++ -O3 -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE  -c read_data.cpp
read_data.cpp:1:10: fatal error: 'gsl/gsl_rng.h' file not found
# include <gsl/gsl_rng.h>

```
     ^
```

1 error generated.
make: **\* [read_data.o] Error 1

**Comment by mojaveazure** [comment]
Do you have the GNU Scientific Library installed? That's where `gsl/gsl_rng.h` is.

**Comment by rossibarra** [comment]
[  2:42PM ]  [ jri@Jeffreys-MacBook-Pro-2:~/src/angsd-wrapper(master✔) ]
 $ ls /usr/local/include/gsl/gsl_rng.h
/usr/local/include/gsl/gsl_rng.h

also previous commits installed fine on this computer.

**Comment by mojaveazure** [comment]
Hi Jeff, can you try installing ANGSD-wrapper now?

**Comment by rossibarra** [comment]
Works.

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org
