### ISSUE TITLE
STABLE branch

### ISSUE THREAD

**Issue by rossibarra** [mojaveazure/angsd-wrapper#28]
Can I suggest a stable branch that people (e.g. my class) can use that we know works but may still need tweaks in naming of things etc., and that we do those fixes on a dev branch?  It seems some of recent fixes are breaking things, which will cause havoc with users/students.  I suggest making sure things work on a new install of AW before committing to master.

**Comment by mojaveazure** [comment]
@liux1299 and I would like to keep working until Sunday night; we'll create the stable and dev branches then.

**Comment by rossibarra** [comment]
OK

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by liux1299** [comment]
Jeff, can you pull the latest version of AW, re-run 2DSFS and run Shiny to
see if the fst graph is what it is supposed to look like?

I've already incorporated the filtering from your merge.R script. The
splash screen of Shiny Fst tab is the Fst file generated from Maize example
data.

Thanks,

Chaochih Liu

**Comment by liux1299** [comment]
Actually, here's a screenshot of what it looks like currently.



Chaochih Liu

**Comment by rossibarra** [comment]
No attachment? I can try that this weekend if I have time.

**Comment by ChaochihL** [comment]
Sorry about that. Here is the attachement:

![screen shot 2016-01-22 at 5 08 35 pm](https://cloud.githubusercontent.com/assets/7061412/12525643/5b35a56e-c12b-11e5-9f26-f29143cec6ab.png)

I've already incorporated the filtering from your merge.R script. The
splash screen of Shiny Fst tab is the Fst file generated from Maize example
data.

Does this look right?

**Comment by rossibarra** [comment]
Looks great. I like the zoom approach. Are we filtering invariant sites in
the thetas display too? (we should)

-Jeff

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by ChaochihL** [comment]
Jeff, I've added an Rscript to filter out invariant sites in the thetas plot. I have the script filtering out Tajimas values = 0 but kept both positive and negative Tajimas values. Let me know if that will work.

**Comment by rossibarra** [comment]
Hi Chaochih,

Nope, that's the wrong way to go.  If pi=watterson's theta D=0 even if both
diversity estimates are >0.  Just filter out anything with theta_w =0 and
you should be good.

-Jeff

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by ChaochihL** [comment]
Thanks for the correction, I will change that in the script. Other than that, everything else should be ready to go. Paul will freeze the working version tonight.

**Comment by mojaveazure** [comment]
Stable release [created](https://github.com/mojaveazure/angsd-wrapper/releases/tag/v.0.2.0-beta), the `dev` branch is where development will predominately occur.
