### ISSUE TITLE
pipefail fails in zsh

### ISSUE THREAD

**Issue by rossibarra** [mojaveazure/angsd-wrapper#33]
https://github.com/rerun/rerun/issues/160

**Comment by mojaveazure** [comment]
![bug](https://files.gitter.im/TomJKono/sUmr/not-a-bug.png)

**Comment by mojaveazure** [comment]
Wright MH, et al. ALCHEMY: a reliable method for automated SNP genotype calling for small batch sizes and highly homozygous populations. Bioinformatics 2010;26(23):2952-60

**Comment by rossibarra** [comment]
Sorry I miss the reference. Do they say something about pipe fail and zsh?

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by mojaveazure** [comment]
When @liux1299 runs AW in zsh, it works for her. The issue referenced says that zsh versions 5.0.7 has `set -o pipefail`; which version of zsh are you running?

**Comment by rossibarra** [comment]
Yeah saw and checked that:

[  2:22PM ]  [ jri@Jeffreys-MacBook-Pro-2:~/Projects/wang_paper/demography/manuscript(master✗)
]
 $ zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by ChaochihL** [comment]
Was able to run with my version:

```
[liux1299@labqi046]~/ANGSD-wrapper_beta_testing/angsd-wrapper/Example_Data/Maize/Configuration_Files% echo $ZSH_VERSION
4.3.11
```

**Comment by rossibarra** [comment]
Intersting, will test again.

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org

**Comment by mojaveazure** [comment]
I can run as well

``` shell
paul@Freya-x220:~/angsd-wrapper/Example_Data/Sequences$ zsh --version
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
```
