### ISSUE TITLE
Calculate SFS without reference genome

### ISSUE THREAD

**Issue by vitorpavinato** [mojaveazure/angsd-wrapper#45]
Dear

I relatively new using ANGSD and I found ANGSD-wrapper a really easy
well to start working with ANGSD methods. I followed the tutorial to
familiarize with the pipeline but I didn’t see anything about how to
run the pipeline when you don’t have an ancestral reference. Is there
a way to use ANGSD-wrapper in these cases?

Thank you!

**Comment by arundurvasula** [comment]
Hello, the way we have SFS implemented right now you need to have an ancestral sequence, but this can be easily changed. If you delete this line https://github.com/mojaveazure/angsd-wrapper/blob/master/Wrappers/Site_Frequency_Spectrum.sh#L54 , ANGSD should run without an ancestral sequence. Note that this is for when you have a regions file. If you don't supply regions you should remove line 77 instead https://github.com/mojaveazure/angsd-wrapper/blob/master/Wrappers/Site_Frequency_Spectrum.sh#L77

Hope that helps!
