### ISSUE TITLE
2DSFS Fst output file mystery

### ISSUE THREAD

**Issue by BrianaGross** [mojaveazure/angsd-wrapper#46]
Thank you for writing and updating angsd-wrapper - it has been a big help for me. 

I am running the 2DSFS Fst estimation on MSI (mesabi). Although the process starts correctly, it ends before calculating Fst, with the error `mv: cannot stat /panfs/roc/groups/3/grossb/grossb/scratch/dom_si_Fst_01/Fst/shared.pos.gz: No such file or directory`. When I go to the project directory in scratch, the 'shared.pos.gz' file is present, but it is outside of the 'Fst' folder where all of the other output files have been created. Any idea how I am managing to get this one output file to go to the wrong place, or how to fix it? Thank you for your time.

**Comment by mojaveazure** [comment]
Hi Briana,

It seems like you're using an old version of ANGSD-wrapper. `shared.pos.gz` was created when we used [ngsPopGen](https://github.com/mfumagalli/ngsPopGen) for F<sub>ST</sub> estimations. If you update to the latest version (run `git pull` in the ANGSD-wrapper directory), we switch to ANGSD's F<sub>ST</sub> estimations at the request of our reviewers. Updating to the latest version should solve this issue as well. We have kept ngsPopGen's F<sub>ST</sub> available as an option as ANGSD's F<sub>ST</sub> estimations are currently ungraphable with our Shiny Graphing application. With the _latest_ version of ANGSD-wrapper, run `git checkout ngsPopGen_Fst` in the ANGSD-wrapper directory.

TL;DNR update to the latest version of ANGSD-wrapper to fix this issue: `git pull`

Please let us know if you still have this issue, or have any other questions or comments!

**Comment by BrianaGross** [comment]
Hi, Paul et al., 

Thanks so much for your quick reply. I am such a newbie at git I was definitely not updated. I appreciate your help with a simple question like this one!

Thanks again,
Briana
