### ISSUE TITLE
Wiki link to thetas

### ISSUE THREAD

**Issue by arundurvasula** [mojaveazure/angsd-wrapper#6]
In the table of contents on the wiki it links to the thetas page on my repo instead of your repo. E.g.

https://github.com/arundurvasula/angsd-wrapper/wiki/Thetas

instead of 

https://github.com/mojaveazure/angsd-wrapper/wiki/Thetas

Don't have access to fix but should be simple.

**Comment by ChaochihL** [comment]
Fixed
